# Generated by Django 3.1 on 2020-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20200824_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_sage_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
