# Generated by Django 3.1 on 2020-09-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20200912_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReturnToNairobi',
            new_name='ReturnToSupplier',
        ),
        migrations.AlterModelOptions(
            name='returntosupplier',
            options={'verbose_name_plural': 'Returned to supplier'},
        ),
        migrations.RenameField(
            model_name='returntostore',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='returntosupplier',
            old_name='qty',
            new_name='quantity',
        ),
    ]
