# Generated by Django 3.1.2 on 2020-11-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_receive_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reorder_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
