# Generated by Django 3.1.2 on 2020-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20201103_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='receive_date',
            field=models.DateTimeField(),
        ),
    ]
