# Generated by Django 3.1 on 2020-08-20 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receive',
            old_name='by',
            new_name='receive_by',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 20, 52, 20, 319825, tzinfo=utc)),
        ),
    ]
