# Generated by Django 3.1 on 2020-08-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200824_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnToStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('reason', models.TextField()),
                ('return_by', models.CharField(max_length=100)),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.issue')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnToNairobi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('qty', models.IntegerField()),
                ('return_by', models.CharField(max_length=100)),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.receive')),
            ],
        ),
    ]
