# Generated by Django 3.1 on 2020-08-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_returntonairobi_returntostore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name_plural': 'Issued'},
        ),
        migrations.AlterModelOptions(
            name='receive',
            options={'verbose_name_plural': 'Received'},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'verbose_name_plural': 'Shelves'},
        ),
    ]
