# Generated by Django 3.1.2 on 2020-11-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20201124_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='receive_date',
            field=models.DateTimeField(default='2020-01-01'),
        ),
    ]
