# Generated by Django 3.1 on 2020-08-31 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200830_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.orderpurpose'),
        ),
    ]
