# Generated by Django 3.1 on 2020-08-31 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purpose',
            new_name='order_purpose',
        ),
        migrations.AddField(
            model_name='order',
            name='order_issued',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.orderissued'),
        ),
    ]
